name: CI

# Control when the action will run.
# Controls how the action will run, based on the enumerated values.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  # A job is a set of steps that are executed on the same runner.
  build:
    # Runner type to use.
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job.
    # To perform a task, a step can use an action that is defined in an external repository,
    # the use of Docker, or a command that is run against the runner's operating system.
    steps:
      # Checks-out your repository into the workspace.
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'uv'

      - name: Install Dependencies with uv
        run: |
          python -m uv pip install --upgrade pip
          python -m uv pip install --system wheel
          python -m uv pip install --system -r requirements.txt
          python -m uv pip install --system -e . # Install in editable mode for the current project

      - name: Lint with Ruff
        run: |
          python -m uv pip install ruff
          ruff check .
          ruff format --check .

      - name: Test with Pytest
        run: |
          python -m uv pip install pytest
          pytest

      - name: Archive Pytest Results
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: |
            ./reports/ # Assuming pytest-xml or similar is configured to output here
            **/*.xml
          retention-days: 7
